env:
  NPM_REGISTRY: "https://repo.aurin.cloud.edu.au/repository/npm-aurin/"
steps:
  - label: "Test"
    key: test
    branches: "*"
    commands:
      - npm ci
      - npm test
  - label: "Deploy"
    key: deploy
    depends_on: test
    branches: "master v*.*.*"
    commands:
      - npm publish
